package com.rbac.model.classroom;

public enum ActivityType {
    JOIN, LEAVE, DISCONNECTED, RECONNECTING,
    HAND_RAISED, HAND_LOWERED, HAND_APPROVED, HAND_DISMISSED,
    MUTED, UNMUTED, MUTE_ALL, SELF_UNMUTE_ALLOWED,
    CAMERA_ON, CAMERA_OFF, CAMERA_ON_REQUESTED,
    PARTICIPANT_REMOVED, PARTICIPANT_REJOINED,
    PERMISSION_CHANGED,
    WAITING_ROOM_REQUEST, WAITING_ROOM_APPROVED, WAITING_ROOM_REJECTED,
    SESSION_STARTED, SESSION_ENDED, SESSION_LOCKED, SESSION_UNLOCKED,
    TRAINER_DISCONNECTED, TRAINER_RECONNECTED, SESSION_AUTO_ENDED
}