    spring.application.name=rbac-backend
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/rbac_db

jwt.secret=ZmY4YzY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0
jwt.expiration-ms=86400000

app.cors.allowed-origin=http://localhost:5173
logging.level.org.springframework.security=INFO

server.error.include-message=always
server.error.include-stacktrace=on_param

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aslaf1243@gmail.com
spring.mail.password=Cloud@1710#2
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=aslaf1243@gmail.com

livekit.url=wss://live-session-2asaeljr.livekit.cloud
livekit.api.key=API9sa7K6vexuik
livekit.api.secret=9wwF80pxz2iEwLWtOW2BRLSY73fIulJvcHfGGYjgH7L

recording.playback.token-expiration-ms=900000
