spring.application.name=rbac-backend
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/rbac_db

jwt.secret=ZmY4YzY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0YjY0
jwt.expiration-ms=86400000

app.cors.allowed-origin=http://localhost:5173
logging.level.org.springframework.security=INFO

server.error.include-message=always
server.error.include-stacktrace=on_param

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=no-reply@yourapp.com
